import React from "react";
import {
  Code,
  Server,
  Database,
  Palette,
  Layers,
  LineChart,
  Wand2,
  CircleEllipsis,
  Box,
  Workflow,
  Sparkles,
} from "lucide-react";

export const skills = [
  {
    name: "Frontend Development",
    namePt: "Desenvolvimento Frontend",
    icon: <Code className="h-6 w-6 text-white" />,
    color: "#3b82f6",
    proficiency: 100,
  },
  {
    name: "Backend Development",
    namePt: "Desenvolvimento Backend",
    icon: <Server className="h-6 w-6 text-white" />,
    color: "#10b981",
    proficiency: 70,
  },
  {
    name: "Database Design",
    namePt: "Modelagem de Banco de Dados",
    icon: <Database className="h-6 w-6 text-white" />,
    color: "#6366f1",
    proficiency: 75,
  },
  {
    name: "UI/UX Design",
    namePt: "Design UI/UX",
    icon: <Palette className="h-6 w-6 text-white" />,
    color: "#ec4899",
    proficiency: 80,
  },
  {
    name: "DevOps",
    namePt: "DevOps",
    icon: <Layers className="h-6 w-6 text-white" />,
    color: "#f59e0b",
    proficiency: 40,
  },
  {
    name: "Data Analytics",
    namePt: "Análise de Dados",
    icon: <LineChart className="h-6 w-6 text-white" />,
    color: "#8b5cf6",
    proficiency: 50,
  },
  {
    name: "Animation & Motion",
    namePt: "Animação & Motion",
    icon: <Wand2 className="h-6 w-6 text-white" />,
    color: "#ef4444",
    proficiency: 80,
  },
  {
    name: "3D, WebGL & AR",
    namePt: "3D, WebGL & AR",
    icon: <Box className="h-6 w-6 text-white" />,
    color: "#06b6d4",
    proficiency: 65,
  },
  {
    name: "AI Integration",
    namePt: "Integração com IA",
    icon: <Sparkles className="h-6 w-6 text-white" />,
    color: "#a855f7",
    proficiency: 60,
  },
  {
    name: "Automation (n8n/Zapier)",
    namePt: "Automação (n8n/Zapier)",
    icon: <Workflow className="h-6 w-6 text-white" />,
    color: "#f97316",
    proficiency: 85,
  },
  {
    name: "Problem Solving",
    namePt: "Resolução de Problemas",
    icon: <CircleEllipsis className="h-6 w-6 text-white" />,
    color: "#14b8a6",
    proficiency: 95,
  },
];
